GET https://www.cheapshark.com/api/1.0/games?title=horizon-zero-dawn
###
GET http://localhost:3000/deals/search/batman
###
GET https://www.cheapshark.com/api/1.0/games?id=612
###
GET http://localhost:3000/deals/CurrentDeals/612

###Register
POST  http://localhost:3000/users/register
Content-Type: application/json

{
    "username": "eliyah",
    "email": "eliyahu@yahoo.com",
    "password": "12346akjsgdyuw"
}
###Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "eliyah",
    "password": "12346akjsgdyuw"
}