GET https://www.cheapshark.com/api/1.0/games?title=horizon-zero-dawn
###
GET http://localhost:3000/search/batman
###
GET https://www.cheapshark.com/api/1.0/games?id=612
###
GET http://localhost:3000/CurrentDeals/612

###
GET http://localhost:3000/CurrentDeals/612